# https://docs.getdbt.com/reference/dbt_project.yml

name: 'dbt_ga4'

config-version: 2
version: 0.0.1

profile: 'dev'

model-paths: ["models"]
target-path: "targets"

log-path: "logs"


require-dbt-version: '>=1.0.0'

quoting:
  database: true
  schema: true
  identifier: true

models:
  dbt_ga4:
    staging:
      +schema: stg_ga4
