# https://docs.getdbt.com/reference/dbt_project.yml
# loosely based on: https://www.ga4bigquery.com/tutorial-how-to-flatten-the-ga4-bigquery-export-schema-for-relational-databases-using-unnest/

name: 'dbt_ga4'

config-version: 2
version: 0.0.1

profile: 'dev'

model-paths: ["models"]
target-path: "targets"

log-path: "logs"


require-dbt-version: '>=1.0.0'

quoting:
  database: true
  schema: true
  identifier: true

models:
  dbt_ga4:
    staging:
      +schema: stg_ga4
