# https://docs.getdbt.com/reference/dbt_project.yml
# loosely based on: https://www.ga4bigquery.com/tutorial-how-to-flatten-the-ga4-bigquery-export-schema-for-relational-databases-using-unnest/


name: 'dbt_ga4'

config-version: 2
version: 0.0.3

profile: 'dev'

vars:
  ga4__look_back_window_days: 5 # Needs to be modified if the model has not run for more than this number of days
  ga4__start_date: '2020-11-01 00:00:00+00:00' # May be used in the future
  ga4__current_date: '2021-01-31 00:00:00+00:00' # Replace with CURRENT_DATE
  ga4__funnel_steps: ['view_search_result', 'select_item', 'add_to_cart', 'add_payment_info', 'purchase'] # Insert all your funnel step events in their respective order here

model-paths: ["models"]
target-path: "targets"

log-path: "logs"


require-dbt-version: '>=1.0.0'

quoting:
  database: true
  schema: true
  identifier: true

models:
  dbt_ga4:
    staging:
      +schema: staging

    intermediate:
      +schema: intermediate

    dwh:
      +schema: core


