  # https://docs.getdbt.com/reference/dbt_project.yml
# loosely based on: https://www.ga4bigquery.com/tutorial-how-to-flatten-the-ga4-bigquery-export-schema-for-relational-databases-using-unnest/

name: 'dbt_ga4'

config-version: 2
version: 0.0.2

profile: 'dev'

vars:
  stg_ga4__look_back_window_days: 125 #Needs to be modified if the model has not run for more than this number of days
  stg_ga4__current_date: '2021-01-31 00:00:00+00:00' # Replace with CURRENT_DATE

model-paths: ["models"]
target-path: "targets"

log-path: "logs"


require-dbt-version: '>=1.0.0'

quoting:
  database: true
  schema: true
  identifier: true

models:
  dbt_ga4:
    staging:
      +schema: stg_ga4

    dwh:
      +schema: fct_ga4


